// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;
using TesteFe.Models;

namespace TesteFe.Migrations
{
    [DbContext(typeof(EstacionamentoContext))]
    [Migration("20180616211212_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteFe.Models.Cartao", b =>
                {
                    b.Property<int>("CartaoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<int?>("EnderecoID");

                    b.Property<int?>("EstacionamentoID");

                    b.Property<string>("Nome");

                    b.Property<int>("Telefone");

                    b.HasKey("CartaoID");

                    b.HasIndex("EnderecoID");

                    b.HasIndex("EstacionamentoID");

                    b.ToTable("Cartao");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Cartao");
                });

            modelBuilder.Entity("TesteFe.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<int>("CEP");

                    b.Property<string>("Cidade");

                    b.Property<string>("Complemento");

                    b.Property<string>("Estado");

                    b.Property<string>("Lougradouro");

                    b.Property<int>("Numero");

                    b.Property<string>("Pais");

                    b.HasKey("EnderecoID");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("TesteFe.Models.Estacionamento", b =>
                {
                    b.Property<int>("EstacionamentoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("EstacionamentoID");

                    b.ToTable("Estacionamento");
                });

            modelBuilder.Entity("TesteFe.Models.CartaoPessoaFisica", b =>
                {
                    b.HasBaseType("TesteFe.Models.Cartao");

                    b.Property<int>("CPF");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<int>("RG");

                    b.Property<string>("Sexo");

                    b.ToTable("CartaoPessoaFisica");

                    b.HasDiscriminator().HasValue("CartaoPessoaFisica");
                });

            modelBuilder.Entity("TesteFe.Models.CartaoPessoaJuridica", b =>
                {
                    b.HasBaseType("TesteFe.Models.Cartao");

                    b.Property<int>("CNPJ");

                    b.Property<string>("RazaoSocial");

                    b.ToTable("CartaoPessoaJuridica");

                    b.HasDiscriminator().HasValue("CartaoPessoaJuridica");
                });

            modelBuilder.Entity("TesteFe.Models.Cartao", b =>
                {
                    b.HasOne("TesteFe.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoID");

                    b.HasOne("TesteFe.Models.Estacionamento")
                        .WithMany("Cartoes")
                        .HasForeignKey("EstacionamentoID");
                });
#pragma warning restore 612, 618
        }
    }
}
